package rules;
import com.rhc.lab.domain.BookingRequest;
import com.rhc.lab.domain.Booking;
import com.rhc.lab.domain.BookingStatus;
import com.rhc.lab.domain.Venue;

dialect "java"

rule "Create Booking from Booking Request"

when
	$obj:BookingRequest ()
then
	Booking booking = new Booking($obj);
	insert(booking);
end

rule "Venue revokes unsuitable Performances"

when 
	$bookingRequest: BookingRequest()
	$venue: Venue(accomodations not contains $bookingRequest.performer.type)
then
	insert(BookingStatus.REVOKED);
end
